# Generated by Django 5.1.3 on 2024-12-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=3, max_length=32),
            preserve_default=False,
        ),
    ]
