# Generated by Django 5.1.3 on 2024-12-08 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0005_assignment_description_en_assignment_description_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='questions_en',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='questions_ru',
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]),
        ),
        migrations.CreateModel(
            name='ExamQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, max_length=65, null=True)),
                ('questions_en', models.CharField(blank=True, max_length=65, null=True)),
                ('questions_ru', models.CharField(blank=True, max_length=65, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='online_course.exam')),
            ],
        ),
    ]
