# Generated by Django 5.1.3 on 2024-12-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0006_remove_exam_questions_remove_exam_questions_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio_ru',
            field=models.TextField(null=True),
        ),
    ]
