# Generated by Django 5.1.3 on 2024-12-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0006_remove_exam_questions_remove_exam_questions_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('клиент', 'клиент'), ('Айтунук', 'Айтунук'), ('администратор', 'администратор')], default='клиент', max_length=16),
        ),
    ]
