# Generated by Django 5.1.3 on 2024-12-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0007_alter_userprofile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('клиент', 'клиент'), ('преподаватель', 'преподаватель'), ('администратор', 'администратор')], default='клиент', max_length=16),
        ),
    ]
