# Generated by Django 5.1.2 on 2024-12-09 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0007_userprofile_bio_en_userprofile_bio_ru'),
        ('online_course', '0008_alter_userprofile_user_role'),
    ]

    operations = [
    ]
