# Generated by Django 5.1.2 on 2024-12-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0010_course_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(max_length=400),
        ),
    ]
