# Generated by Django 5.1.3 on 2024-12-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0009_merge_20241210_1346'),
        ('online_course', '0011_alter_userprofile_password'),
    ]

    operations = [
    ]
