# Generated by Django 5.1.2 on 2024-12-11 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0014_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_course.course')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_course.favorite')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_course.lesson')),
            ],
        ),
    ]
