# Generated by Django 5.1.2 on 2024-12-11 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0015_favorite_favoritelesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
