# Generated by Django 5.1.2 on 2024-12-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0016_alter_userprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='created_date',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
