# Generated by Django 5.1.2 on 2024-12-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0017_exam_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
