# Generated by Django 5.1.2 on 2024-12-12 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_course', '0018_remove_exam_created_date_alter_exam_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='duration',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
